title: Akash Kashyap
logo: files/DSCN0908-01.jpeg
description: Hi Everyone, I am a Data science enthusiast with a passion for solving real-world problems using machine learning and data analysis.
#show_downloads: true
theme: jekyll-theme-minimal
